# Generated by Django 4.1 on 2022-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.SmallIntegerField(max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
