# Generated by Django 4.1 on 2022-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
