# Generated by Django 4.1 on 2022-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0003_rename_students_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='age',
        ),
        migrations.AddField(
            model_name='workers',
            name='fich',
            field=models.FileField(default='media/Resume Ghassen', upload_to=''),
        ),
    ]
