# Generated by Django 4.1 on 2022-08-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0005_alter_workers_fich'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workers',
            new_name='workerss',
        ),
    ]
