# Generated by Django 4.1 on 2022-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0006_rename_workers_workerss'),
    ]

    operations = [
        migrations.CreateModel(
            name='workersss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('fich', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='workerss',
        ),
    ]
