# Generated by Django 4.1 on 2022-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0007_workersss_delete_workerss'),
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='workersss',
        ),
    ]
