# Generated by Django 4.1 on 2022-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0008_workers_delete_workersss'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='fich',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
