# Generated by Django 4.1 on 2022-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0009_workers_fich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='fich',
            field=models.FileField(upload_to='photos'),
        ),
    ]
